-- MySQL Script generated by MySQL Workbench
-- Sat May  9 14:15:36 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema TT2019-B087
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `TT2019-B087` ;

-- -----------------------------------------------------
-- Schema TT2019-B087
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TT2019-B087` DEFAULT CHARACTER SET utf8 ;
USE `TT2019-B087` ;

-- -----------------------------------------------------
-- Table `TT2019-B087`.`Rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TT2019-B087`.`Rol` ;

CREATE TABLE IF NOT EXISTS `TT2019-B087`.`Rol` (
  `idRol` INT NOT NULL,
  `nameRol` VARCHAR(45) NOT NULL,
  `activo` INT NOT NULL,
  PRIMARY KEY (`idRol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TT2019-B087`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TT2019-B087`.`User` ;

CREATE TABLE IF NOT EXISTS `TT2019-B087`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `userName` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `activo` INT NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `sex` VARCHAR(1) NOT NULL,
  `Rol_idRol` INT NOT NULL,
  PRIMARY KEY (`idUser`, `Rol_idRol`),
  INDEX `fk_User_Rol1_idx` (`Rol_idRol` ASC) VISIBLE,
  CONSTRAINT `fk_User_Rol1`
    FOREIGN KEY (`Rol_idRol`)
    REFERENCES `TT2019-B087`.`Rol` (`idRol`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TT2019-B087`.`Device`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TT2019-B087`.`Device` ;

CREATE TABLE IF NOT EXISTS `TT2019-B087`.`Device` (
  `idDevice` INT NOT NULL AUTO_INCREMENT,
  `deviceName` VARCHAR(45) NOT NULL,
  `MAC` VARCHAR(45) NOT NULL,
  `activo` INT NOT NULL,
  PRIMARY KEY (`idDevice`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TT2019-B087`.`Sensor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TT2019-B087`.`Sensor` ;

CREATE TABLE IF NOT EXISTS `TT2019-B087`.`Sensor` (
  `idSensor` INT NOT NULL AUTO_INCREMENT,
  `sensorName` VARCHAR(45) NOT NULL,
  `MAC` VARCHAR(45) NOT NULL,
  `activo` INT NOT NULL,
  PRIMARY KEY (`idSensor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TT2019-B087`.`Action`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TT2019-B087`.`Action` ;

CREATE TABLE IF NOT EXISTS `TT2019-B087`.`Action` (
  `idAction` INT NOT NULL AUTO_INCREMENT,
  `nameAction` VARCHAR(45) NOT NULL,
  `params` VARCHAR(200) NOT NULL,
  `activo` INT NOT NULL,
  PRIMARY KEY (`idAction`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TT2019-B087`.`UserDevices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TT2019-B087`.`UserDevices` ;

CREATE TABLE IF NOT EXISTS `TT2019-B087`.`UserDevices` (
  `idUserDevices` INT NOT NULL AUTO_INCREMENT,
  `User_idUser` INT NOT NULL,
  `User_Rol_idRol` INT NOT NULL,
  `Device_idDevice` INT NOT NULL,
  PRIMARY KEY (`idUserDevices`, `User_idUser`, `User_Rol_idRol`, `Device_idDevice`),
  INDEX `fk_UserDevices_User1_idx` (`User_idUser` ASC, `User_Rol_idRol` ASC) VISIBLE,
  INDEX `fk_UserDevices_Device1_idx` (`Device_idDevice` ASC) VISIBLE,
  CONSTRAINT `fk_UserDevices_User1`
    FOREIGN KEY (`User_idUser` , `User_Rol_idRol`)
    REFERENCES `TT2019-B087`.`User` (`idUser` , `Rol_idRol`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_UserDevices_Device1`
    FOREIGN KEY (`Device_idDevice`)
    REFERENCES `TT2019-B087`.`Device` (`idDevice`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TT2019-B087`.`SensorActions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TT2019-B087`.`SensorActions` ;

CREATE TABLE IF NOT EXISTS `TT2019-B087`.`SensorActions` (
  `idSensorActions` INT NOT NULL AUTO_INCREMENT,
  `Sensor_idSensor` INT NOT NULL,
  `Action_idAction` INT NOT NULL,
  `instruccion` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`idSensorActions`, `Sensor_idSensor`, `Action_idAction`),
  INDEX `fk_SensorActions_Sensor1_idx` (`Sensor_idSensor` ASC) VISIBLE,
  INDEX `fk_SensorActions_Action1_idx` (`Action_idAction` ASC) VISIBLE,
  CONSTRAINT `fk_SensorActions_Sensor1`
    FOREIGN KEY (`Sensor_idSensor`)
    REFERENCES `TT2019-B087`.`Sensor` (`idSensor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_SensorActions_Action1`
    FOREIGN KEY (`Action_idAction`)
    REFERENCES `TT2019-B087`.`Action` (`idAction`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TT2019-B087`.`DeviceActions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TT2019-B087`.`DeviceActions` ;

CREATE TABLE IF NOT EXISTS `TT2019-B087`.`DeviceActions` (
  `idDeviceActions` INT NOT NULL AUTO_INCREMENT,
  `UserDevices_idUserDevices` INT NOT NULL,
  `UserDevices_User_idUser` INT NOT NULL,
  `UserDevices_User_Rol_idRol` INT NOT NULL,
  `UserDevices_Device_idDevice` INT NOT NULL,
  `SensorActions_idSensorActions` INT NOT NULL,
  `SensorActions_Sensor_idSensor` INT NOT NULL,
  `SensorActions_Action_idAction` INT NOT NULL,
  `timestamp` DATETIME NOT NULL,
  PRIMARY KEY (`idDeviceActions`, `UserDevices_idUserDevices`, `UserDevices_User_idUser`, `UserDevices_User_Rol_idRol`, `UserDevices_Device_idDevice`, `SensorActions_idSensorActions`, `SensorActions_Sensor_idSensor`, `SensorActions_Action_idAction`),
  INDEX `fk_DeviceActions_UserDevices1_idx` (`UserDevices_idUserDevices` ASC, `UserDevices_User_idUser` ASC, `UserDevices_User_Rol_idRol` ASC, `UserDevices_Device_idDevice` ASC) VISIBLE,
  INDEX `fk_DeviceActions_SensorActions1_idx` (`SensorActions_idSensorActions` ASC, `SensorActions_Sensor_idSensor` ASC, `SensorActions_Action_idAction` ASC) VISIBLE,
  CONSTRAINT `fk_DeviceActions_UserDevices1`
    FOREIGN KEY (`UserDevices_idUserDevices` , `UserDevices_User_idUser` , `UserDevices_User_Rol_idRol` , `UserDevices_Device_idDevice`)
    REFERENCES `TT2019-B087`.`UserDevices` (`idUserDevices` , `User_idUser` , `User_Rol_idRol` , `Device_idDevice`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_DeviceActions_SensorActions1`
    FOREIGN KEY (`SensorActions_idSensorActions` , `SensorActions_Sensor_idSensor` , `SensorActions_Action_idAction`)
    REFERENCES `TT2019-B087`.`SensorActions` (`idSensorActions` , `Sensor_idSensor` , `Action_idAction`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `TT2019-B087`.`Rol`
-- -----------------------------------------------------
START TRANSACTION;
USE `TT2019-B087`;
INSERT INTO `TT2019-B087`.`Rol` (`idRol`, `nameRol`, `activo`) VALUES (1, 'ADMIN', 1);
INSERT INTO `TT2019-B087`.`Rol` (`idRol`, `nameRol`, `activo`) VALUES (2, 'AGRICULTOR', 1);
INSERT INTO `TT2019-B087`.`Rol` (`idRol`, `nameRol`, `activo`) VALUES (3, 'CASERO', 1);
INSERT INTO `TT2019-B087`.`Rol` (`idRol`, `nameRol`, `activo`) VALUES (4, 'MASTER', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `TT2019-B087`.`User`
-- -----------------------------------------------------
START TRANSACTION;
USE `TT2019-B087`;
INSERT INTO `TT2019-B087`.`User` (`idUser`, `userName`, `password`, `name`, `lastname`, `activo`, `email`, `sex`, `Rol_idRol`) VALUES (1, 'JMTMXM', 'q1w2e3ADMIN', 'Juan', 'Torres', 1, 'juan.man.tor.mar@gmail.com', 'M', 1);
INSERT INTO `TT2019-B087`.`User` (`idUser`, `userName`, `password`, `name`, `lastname`, `activo`, `email`, `sex`, `Rol_idRol`) VALUES (2, 'Misaleybbs', 'asd123ADMIN', 'Alan', 'Sánchez', 1, 'misaelybbs@gmail.com', 'M', 1);
INSERT INTO `TT2019-B087`.`User` (`idUser`, `userName`, `password`, `name`, `lastname`, `activo`, `email`, `sex`, `Rol_idRol`) VALUES (3, 'JMTMCampo', 'q1w2e3', 'Juan', 'Martínez', 1, 'juan.man.tor.mar@gmail.com', 'M', 2);
INSERT INTO `TT2019-B087`.`User` (`idUser`, `userName`, `password`, `name`, `lastname`, `activo`, `email`, `sex`, `Rol_idRol`) VALUES (4, 'MisaelyCampo', 'asd123', 'Alan', 'Escalona', 1, 'misaelybbs@gmail.com', 'M', 2);
INSERT INTO `TT2019-B087`.`User` (`idUser`, `userName`, `password`, `name`, `lastname`, `activo`, `email`, `sex`, `Rol_idRol`) VALUES (5, 'JMTMCasa', 'bnm234', 'Juan', 'Casa', 1, 'juan.man.tor.mar@gmail.com', 'M', 3);
INSERT INTO `TT2019-B087`.`User` (`idUser`, `userName`, `password`, `name`, `lastname`, `activo`, `email`, `sex`, `Rol_idRol`) VALUES (6, 'AlanCasa', 'klj345', 'Alan', 'Casa', 1, 'misaelybbs@gmail.com', 'M', 3);
INSERT INTO `TT2019-B087`.`User` (`idUser`, `userName`, `password`, `name`, `lastname`, `activo`, `email`, `sex`, `Rol_idRol`) VALUES (7, 'Gabry', 'uio789', 'Gabriel', 'Martínez', 1, 'iam_gaby-lan@hotmail.com', 'M', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `TT2019-B087`.`Device`
-- -----------------------------------------------------
START TRANSACTION;
USE `TT2019-B087`;
INSERT INTO `TT2019-B087`.`Device` (`idDevice`, `deviceName`, `MAC`, `activo`) VALUES (1, 'S10+ de JMTM', 'A8:DB:03:66:F4:03', 1);
INSERT INTO `TT2019-B087`.`Device` (`idDevice`, `deviceName`, `MAC`, `activo`) VALUES (2, 'Android de Alan Misael', '00:10:FA:6E:38:4A', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `TT2019-B087`.`Sensor`
-- -----------------------------------------------------
START TRANSACTION;
USE `TT2019-B087`;
INSERT INTO `TT2019-B087`.`Sensor` (`idSensor`, `sensorName`, `MAC`, `activo`) VALUES (1, 'Sensor de Temperatura 01', '00:10:FA:6E:38:4A', 1);
INSERT INTO `TT2019-B087`.`Sensor` (`idSensor`, `sensorName`, `MAC`, `activo`) VALUES (2, 'Sensor de iluminación 01', '72:A7:0A:03:3E:EA', 1);
INSERT INTO `TT2019-B087`.`Sensor` (`idSensor`, `sensorName`, `MAC`, `activo`) VALUES (3, 'Sensor de humedad 01', '61:3E:28:CE:AD:BC', 1);
INSERT INTO `TT2019-B087`.`Sensor` (`idSensor`, `sensorName`, `MAC`, `activo`) VALUES (4, 'Llave de gas 01', '4A:35:05:CA:6E:AD', 1);
INSERT INTO `TT2019-B087`.`Sensor` (`idSensor`, `sensorName`, `MAC`, `activo`) VALUES (5, 'Llave de gas 02', 'C4:BA:EE:9A:97:61', 1);
INSERT INTO `TT2019-B087`.`Sensor` (`idSensor`, `sensorName`, `MAC`, `activo`) VALUES (6, 'Llave de gas 03', 'DB:03:B4:6C:6A:A9', 1);
INSERT INTO `TT2019-B087`.`Sensor` (`idSensor`, `sensorName`, `MAC`, `activo`) VALUES (7, 'Foco 01', '65:71:1F:32:5B:59', 1);
INSERT INTO `TT2019-B087`.`Sensor` (`idSensor`, `sensorName`, `MAC`, `activo`) VALUES (8, 'Foco 02', 'EB:32:0C:97:35:B9', 1);
INSERT INTO `TT2019-B087`.`Sensor` (`idSensor`, `sensorName`, `MAC`, `activo`) VALUES (9, 'Foco 03', '84:A5:35:56:2E:8D', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `TT2019-B087`.`Action`
-- -----------------------------------------------------
START TRANSACTION;
USE `TT2019-B087`;
INSERT INTO `TT2019-B087`.`Action` (`idAction`, `nameAction`, `params`, `activo`) VALUES (1, 'Abrir', '1', 1);
INSERT INTO `TT2019-B087`.`Action` (`idAction`, `nameAction`, `params`, `activo`) VALUES (2, 'Cerrar', '2', 1);
INSERT INTO `TT2019-B087`.`Action` (`idAction`, `nameAction`, `params`, `activo`) VALUES (3, 'Medir', '3', 1);
INSERT INTO `TT2019-B087`.`Action` (`idAction`, `nameAction`, `params`, `activo`) VALUES (4, 'Encender Foco', '4', 1);
INSERT INTO `TT2019-B087`.`Action` (`idAction`, `nameAction`, `params`, `activo`) VALUES (5, 'Apagar Foco', '5', 1);

COMMIT;

